#!/bin/sh

# define path to program, assuming this file is
# inside of the application's folder

PLATFORM=`uname`;
APP_UI_ADDRESS="http://localhost:8000";

cd `dirname $0`

if [[ ! -d './js' ]]
then
	echo "Fatal: Could not find directory 'js'";
	exit 1;
fi

cd 'js';

if [[ $PLATFORM == 'Darwin' ]]
then
	sh -c "bash -c \"open -a 'Google Chrome' 'http://localhost:8000'\"";
	sh -c "bash -c \"node .\""
else
	gnome-terminal -e "bash -c \"google-chrome http://localhost:8000\"";
	gnome-terminal -e "bash -c \"node .\"";
fi